welcome_page:
    path: /
    defaults: { _controller: GeekhubMainBundle:Main:index }

first_page:
    path: /hello/{name}
    defaults: { _controller: GeekhubMainBundle:Main:first, name: World }

show_posts:
    path: /posts
    defaults: { _controller: GeekhubMainBundle:Main:showPosts }

show_post:
    path: /post/{id}
    defaults: { _controller: GeekhubMainBundle:Main:showPost, id:0 }

test_twig:
    path: /twig
    defaults: { _controller: GeekhubMainBundle:Main:testTwig }

many_to_many:
    path: /many_to_many
    defaults: { _controller: GeekhubMainBundle:Main:manyToMany }
