# MainController routes
welcome_page:
    path: /
    defaults: { _controller: GeekhubMainBundle:Main:index }

first_page:
    path: /hello/{name}
    defaults: { _controller: GeekhubMainBundle:Main:first, name: World }

test_twig:
    path: /twig
    defaults: { _controller: GeekhubMainBundle:Main:testTwig }

simple_translation:
    path: /simple-translation
    defaults: { _controller: GeekhubMainBundle:Main:simpleTranslation }

many_to_many:
    path: /many_to_many
    defaults: { _controller: GeekhubMainBundle:Main:manyToMany }

# PostController routes
posts_index:
    path: /posts
    defaults: { _controller: GeekhubMainBundle:Post:index }

post_create:
    path: /posts/create
    defaults: { _controller: GeekhubMainBundle:Post:create }

post_update:
    path: /posts/update/{slug_title}
    defaults: { _controller: GeekhubMainBundle:Post:update, slug_title: 0 }

show_post:
    path: /post/{slug_title}
    defaults: { _controller: GeekhubMainBundle:Post:show, slug_title:0 }
